# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - name: "Grid Voltage"
      state_topic: "homeassistant/sensor/inverter_grid_voltage"
      unique_id: "inverter_grid_voltage"
      device_class: "voltage"
      unit_of_measurement: "V"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "Grid Frequency"
      state_topic: "homeassistant/sensor/inverter_grid_frequency"
      unique_id: "inverter_grid_frequency"
      device_class: "frequency"
      unit_of_measurement: "Hz"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "AC Output Voltage"
      state_topic: "homeassistant/sensor/inverter_ac_output_voltage"
      unique_id: "inverter_ac_output_voltage"
      device_class: "voltage"
      unit_of_measurement: "V"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "AC Output Frequency"
      state_topic: "homeassistant/sensor/inverter_ac_output_frequency"
      unique_id: "inverter_ac_output_frequency"
      device_class: "frequency"
      unit_of_measurement: "Hz"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "AC Output Apparent Power"
      state_topic: "homeassistant/sensor/inverter_ac_output_apparent_power"
      unique_id: "inverter_ac_output_apparent_power"
      device_class: "apparent_power"
      unit_of_measurement: "VA"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "AC Output Active Power"
      state_topic: "homeassistant/sensor/inverter_ac_output_active_power"
      unique_id: "inverter_ac_output_active_power"
      device_class: "power"
      unit_of_measurement: "W"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "AC Output Load Percent"
      state_topic: "homeassistant/sensor/inverter_ac_output_load_percent"
      unique_id: "inverter_ac_output_load_percent"
      unit_of_measurement: "%"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "Bus Voltage"
      state_topic: "homeassistant/sensor/inverter_bus_voltage"
      unique_id: "inverter_bus_voltage"
      device_class: "voltage"
      unit_of_measurement: "V"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "Battery Voltage"
      state_topic: "homeassistant/sensor/inverter_battery_voltage"
      unique_id: "inverter_battery_voltage"
      device_class: "voltage"
      unit_of_measurement: "V"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "Battery Charge Current"
      state_topic: "homeassistant/sensor/inverter_battery_charge_current"
      unique_id: "inverter_battery_charge_current"
      device_class: "current"
      unit_of_measurement: "A"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "Battery Capacity"
      state_topic: "homeassistant/sensor/inverter_battery_capacity"
      unique_id: "inverter_battery_capacity"
      device_class: "battery"
      unit_of_measurement: "%"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "Inverter Temperature"
      state_topic: "homeassistant/sensor/inverter_inverter_temperature"
      unique_id: "inverter_inverter_temperature"
      device_class: "temperature"
      unit_of_measurement: "C"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "PV1 Input Current"
      state_topic: "homeassistant/sensor/inverter_pv1_input_current"
      unique_id: "inverter_pv1_input_current"
      device_class: "current"
      unit_of_measurement: "A"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "PV1 Input Voltage"
      state_topic: "homeassistant/sensor/inverter_pv1_input_voltage"
      unique_id: "inverter_pv1_input_voltage"
      device_class: "voltage"
      unit_of_measurement: "V"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "Battery Voltage from SCC"
      state_topic: "homeassistant/sensor/inverter_battery_voltage_from_scc"
      unique_id: "inverter_battery_voltage_from_scc"
      device_class: "voltage"
      unit_of_measurement: "V"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "Battery Discharge Current"
      state_topic: "homeassistant/sensor/inverter_battery_discharge_current"
      unique_id: "inverter_battery_discharge_current"
      device_class: "current"
      unit_of_measurement: "A"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "PV1 Charge Power"
      state_topic: "homeassistant/sensor/inverter_pv1_charge_power"
      unique_id: "inverter_pv1_charge_power"
      device_class: "power"
      unit_of_measurement: "W"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "PV2 Input Current"
      state_topic: "homeassistant/sensor/inverter_pv2_input_current"
      unique_id: "inverter_pv2_input_current"
      device_class: "current"
      unit_of_measurement: "A"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "PV2 Input Voltage"
      state_topic: "homeassistant/sensor/inverter_pv2_input_voltage"
      unique_id: "inverter_pv2_input_voltage"
      device_class: "voltage"
      unit_of_measurement: "V"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"

    - name: "PV1 Charge Power"
      state_topic: "homeassistant/sensor/inverter_pv2_charging_power"
      unique_id: "inverter_pv2_charging_power"
      device_class: "power"
      unit_of_measurement: "W"
      device:
        name: "Invertor - QPIGS"
        identifiers:
          - "solar_inverter"
        model: "iSloar-SML-III"
        manufacturer: "EASun"
